In [5]:
import numpy as np
import pandas as pd

# Load data
data=pd.read_csv('HR_comma_sep.csv')

data.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Departments,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.11,0.88,7,272,4,0,1,0,sales,medium
3,0.72,0.87,5,223,5,0,1,0,sales,low
4,0.37,0.52,2,159,3,0,1,0,sales,low

# Preprocessing:

Lots of machine learning algorithms require numerical input data, so you need to represent categorical columns in a numerical column. In order to encode this data, you could map each value to a number. e.g. Salary column’s value can be represented as low:0, medium:1, and high:2. This process is known as label encoding. In sklearn, we can do this using LabelEncoder.

In [7]:
# Import LabelEncoder
from sklearn import preprocessing

# Creating labelEncoder
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.
data['salary']=le.fit_transform(data['salary'])
data['Departments']=le.fit_transform(data['Departments'])

**Split the dataset**

In order to assess the model performance, we need to divide the dataset into a training set and a test set. Let’s split dataset by using function train_test_split(). you need to pass basically 3 parameters features, target, and test_set size.

In [9]:
# Spliting data into Feature and
X=data[['satisfaction_level', 'last_evaluation', 'number_project', 'average_montly_hours', 'time_spend_company', 'Work_accident', 'promotion_last_5years', 'Departments', 'salary']]
y=data['left']

# Import train_test_split function
from sklearn.model_selection import train_test_split

# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)  # 70% training and 30% test

**Build Classification Model**



Parameters:

**hidden_layer_sizes**: it is a tuple where each element represents one layer and its value represents the number of neurons on each hidden layer.

**learning_rate_init**: It used to controls the step-size in updating the weights.


**activation**: Activation function for the hidden layer. Examples, identity, logistic, tanh, and relu. by default, relu is used as an activation function.


**random_state**: It defines the random number for weights and bias initialization. 


**verbose**: It used to print progress messages to standard output.

In [10]:
# Import MLPClassifer 
from sklearn.neural_network import MLPClassifier

# Create model object
clf = MLPClassifier(hidden_layer_sizes=(6,5),
                    random_state=5,
                    verbose=True,
                    learning_rate_init=0.01)

# Fit data onto the model
clf.fit(X_train,y_train)

Iteration 1, loss = 0.61512605
Iteration 2, loss = 0.57545658
Iteration 3, loss = 0.55823146
Iteration 4, loss = 0.53011644
Iteration 5, loss = 0.50549749
Iteration 6, loss = 0.48004244
Iteration 7, loss = 0.47915513
Iteration 8, loss = 0.46239153
Iteration 9, loss = 0.47441120
Iteration 10, loss = 0.46241650
Iteration 11, loss = 0.45068143
Iteration 12, loss = 0.45071101
Iteration 13, loss = 0.45213613
Iteration 14, loss = 0.46049483
Iteration 15, loss = 0.45897398
Iteration 16, loss = 0.46170601
Iteration 17, loss = 0.45527116
Iteration 18, loss = 0.44996595
Iteration 19, loss = 0.44982305
Iteration 20, loss = 0.45384764
Iteration 21, loss = 0.46981282
Iteration 22, loss = 0.45010489
Iteration 23, loss = 0.46852413
Iteration 24, loss = 0.45242336
Iteration 25, loss = 0.45769894
Iteration 26, loss = 0.45074974
Iteration 27, loss = 0.44067556
Iteration 28, loss = 0.43205930
Iteration 29, loss = 0.41680331
Iteration 30, loss = 0.40752887
Iteration 31, loss = 0.39186392
Iteration 32, loss = 0.37054743
Iteration 33, loss = 0.35797517
Iteration 34, loss = 0.34539661
Iteration 35, loss = 0.33669847
Iteration 36, loss = 0.33052333
Iteration 37, loss = 0.31754074
Iteration 38, loss = 0.31470388
Iteration 39, loss = 0.31036267
Iteration 40, loss = 0.30717479
Iteration 41, loss = 0.31789566
Iteration 42, loss = 0.31782866
Iteration 43, loss = 0.30641517
Iteration 44, loss = 0.30123487
Iteration 45, loss = 0.30474254
Iteration 46, loss = 0.31051473
Iteration 47, loss = 0.28624198
Iteration 48, loss = 0.29316190
Iteration 49, loss = 0.28463864
Iteration 50, loss = 0.28582673
Iteration 51, loss = 0.28378548
Iteration 52, loss = 0.28098729
Iteration 53, loss = 0.28513299
Iteration 54, loss = 0.27992380
Iteration 55, loss = 0.28034603
Iteration 56, loss = 0.28447776
Iteration 57, loss = 0.27920526
Iteration 58, loss = 0.27545140
Iteration 59, loss = 0.27418263
Iteration 60, loss = 0.26921345
Iteration 61, loss = 0.27200225
Iteration 62, loss = 0.26757142
Iteration 63, loss = 0.26824884
Iteration 64, loss = 0.26115995
Iteration 65, loss = 0.25875549
Iteration 66, loss = 0.25919820
Iteration 67, loss = 0.26178076
Iteration 68, loss = 0.26228984
Iteration 69, loss = 0.26001505
Iteration 70, loss = 0.25199503
Iteration 71, loss = 0.27545142
Iteration 72, loss = 0.25545200
Iteration 73, loss = 0.25464872
Iteration 74, loss = 0.24550959
Iteration 75, loss = 0.24336325
Iteration 76, loss = 0.24215966
Iteration 77, loss = 0.23850104
Iteration 78, loss = 0.23889253
Iteration 79, loss = 0.23109586
Iteration 80, loss = 0.23399638
Iteration 81, loss = 0.23802679
Iteration 82, loss = 0.23385322
Iteration 83, loss = 0.24284518
Iteration 84, loss = 0.23134733
Iteration 85, loss = 0.24330075
Iteration 86, loss = 0.22532877
Iteration 87, loss = 0.22568393
Iteration 88, loss = 0.22081075
Iteration 89, loss = 0.22846698
Iteration 90, loss = 0.22502850
Iteration 91, loss = 0.21784989
Iteration 92, loss = 0.21292884
Iteration 93, loss = 0.18813462
Iteration 94, loss = 0.17769639
Iteration 95, loss = 0.18582654
Iteration 96, loss = 0.18127325
Iteration 97, loss = 0.16734828
Iteration 98, loss = 0.18286465
Iteration 99, loss = 0.16981846
Iteration 100, loss = 0.17330641
Iteration 101, loss = 0.15969499
Iteration 102, loss = 0.15829448
Iteration 103, loss = 0.15677615
Iteration 104, loss = 0.16861506
Iteration 105, loss = 0.15665635
Iteration 106, loss = 0.17290740
Iteration 107, loss = 0.16313185
Iteration 108, loss = 0.15127830
Iteration 109, loss = 0.15304460
Iteration 110, loss = 0.15963898
Iteration 111, loss = 0.16963601
Iteration 112, loss = 0.15063887
Iteration 113, loss = 0.15393529
Iteration 114, loss = 0.17528787
Iteration 115, loss = 0.17271381
Iteration 116, loss = 0.15426095
Iteration 117, loss = 0.14971746
Iteration 118, loss = 0.15078193
Iteration 119, loss = 0.16200046
Iteration 120, loss = 0.15242240
Iteration 121, loss = 0.15700943
Iteration 122, loss = 0.15836204
Iteration 123, loss = 0.15847074
Iteration 124, loss = 0.15069127
Iteration 125, loss = 0.14876175
Iteration 126, loss = 0.14993943
Iteration 127, loss = 0.15168619
Iteration 128, loss = 0.16245349
Iteration 129, loss = 0.15119375
Iteration 130, loss = 0.15576164
Iteration 131, loss = 0.15837115
Iteration 132, loss = 0.15242943
Iteration 133, loss = 0.15235532
Iteration 134, loss = 0.15423949
Iteration 135, loss = 0.15300715
Iteration 136, loss = 0.15038034
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

MLPClassifier(hidden_layer_sizes=(6, 5), learning_rate_init=0.01,
              random_state=5, verbose=True)

**Make Prediction and Evaluate the Model**

In [11]:
# Make prediction on test dataset
ypred=clf.predict(X_test)

# Import accuracy score 
from sklearn.metrics import accuracy_score

# Calcuate accuracy
accuracy_score(y_test,ypred)

0.9386666666666666